#!/bin/bash -x

# Sets up software on a new computer
#   Install Command line tools, XAqua, dotfiles, brew casks
#   Builds appropriate symlinks

# At first I will not have the appropriate symlinks to run this from
#  my Scripts folder.  I will have to figure out how to get
#  this file first time I run it.

# This is a hack which prompts you to install XCode's command line tools without XCode
xcode-select --install

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade
brew doctor

# Install critical binaries (casks)
brew cask install xquartz  # Homebrew may demand this
brew cask install caffeine # Keep Mac awake during lengthy downloads
brew cask install iterm2 # Then close Terminal, never to reopen

# Compile packages (brews)
brew install gcc # Better C compiler with Fortran support

# git
brew install git
git config --global user.name "nebader"
git config --global user.email "nbader@gmail.com"

# Python
###########????????


# Emacs
brew tap d12frosted/Emacs-plus # For Spacemacs
brew install emacs-plus
brew linkapps emacs-plus
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

# LaTeX
brew install ghostscript # MacTeX will need this
brew cask install mactex

# R
brew install openblas # Library of fast numerical algorithms
brew install r --with-openblas # This compiled version is faster than the binary

# 
brew cask install dropbox
java
google-chrome
google-drive
google-earth-pro
mactex
vlc


## OLD STUFF FROM LAPTOP

brew install python  Default python is 2.x #### SWITCH TO CONDA
brew install python3
# Check 'which python' in Terminal after a 'hash -r python' to invalidate the shell's lookup cache
# Result should be in /usr/local/bin - if not, prepend it to $PATH

# Tap additional repositories
#brew tap homebrew/science
#brew tap homebrew/python
#brew tap buo/cask-upgrade # Third party tool to upgrade casks


# Image stuff (this list from https://joernhees.de/blog/2014/02/25/scientific-python-on-mac-os-x-10-9-with-homebrew/)
brew install libtiff libjpeg webp little-cms2
brew install imagemagick --with-fftw --with-librsvg --with-x11
brew install graphviz --with-librsvg --with-x11
# Python stuff version 2.x
pip2 install virtualenv
pip2 install nose
pip2 install numpy
pip2 install scipy
# Test
python2 -c 'import numpy ; numpy.test();'
python2 -c 'import scipy ; scipy.test();'

# Python stuff version 3.x
pip3 install virtualenv
pip3 install nose
pip3 install numpy
pip3 install scipy
# Test
python3 -c 'import numpy ; numpy.test();'
python3 -c 'import scipy ; scipy.test();'pip3 install numpy
pip3 install scipy



# Install remaining 3rd party binaries
apps=(
    dropbox
    java
    google-chrome
    google-drive
    google-earth-pro
    mactex
    vlc
)
brew cask install "${apps[@]}"

# Manually sign in to Dropbox and Google Drive to start downloads
# FINISH before next step

# Build symlinks to Dropbox
# syntax: ln -sv "real"_file link location
cd
sudo rm -rf Documents
ln -sv ~/Dropbox/backup/Documents ~/Documents
ln -sv ~/Dropbox/backup/Scripts ~/Scripts
ln -sv ~/Dropbox/backup/Sites ~/Sites
ln -sv ~/Dropbox/backup/Documents/texmf ~/Library/texmf
ln -sv /Users/nbader/Dropbox/backup/Google\ Earth /Users/nbader/Library/Application\ Support/Google\ Earth


# syntax: ln -sv ["real" file] [link location]
cd
git clone git://github.com/nebader/dotfiles.git
ln -sv ~/dotfiles/vimrc ~/.vimrc
ln -sv ~/dotfiles/spacemacs ~/.spacemacs
ln -sv ~/dotfiles/bashrc ~/.bashrc
ln -sv ~/dotfiles/bashrc ~/.bash_profile # on OS X, .bash_profile is always run

